"""add user unique

Revision ID: 64e403feb18b
Revises: c1c7d4c1531b
Create Date: 2022-01-16 16:01:18.322770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e403feb18b'
down_revision = 'c1c7d4c1531b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    # ### end Alembic commands ###
