"""init

Revision ID: a52a6ee1c83f
Revises: 
Create Date: 2022-01-20 13:32:20.819758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52a6ee1c83f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.SMALLINT(), nullable=False),
    sa.Column('source_id', sa.BIGINT(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('album_create_date', sa.DateTime(), nullable=True),
    sa.Column('album_update_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('short_intro', sa.TEXT(), nullable=True),
    sa.Column('rich_intro', sa.TEXT(), nullable=True),
    sa.Column('rich_detail_intro', sa.TEXT(), nullable=True),
    sa.Column('cover', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('rss', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('track_total_counts', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_title'), 'album', ['title'], unique=True)
    op.create_table('album_statics',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('play_counts', sa.BIGINT(), nullable=True),
    sa.Column('subscribe_counts', sa.BIGINT(), nullable=True),
    sa.Column('comment_counts', sa.BIGINT(), nullable=True),
    sa.Column('like_counts', sa.BIGINT(), nullable=True),
    sa.Column('album_id', sa.BIGINT(), nullable=False),
    sa.Column('vip_type', sa.SMALLINT(), nullable=True),
    sa.Column('is_finished', sa.SMALLINT(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('has_buy', sa.BOOLEAN(), nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_tag_pivot',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('album_id', sa.BIGINT(), nullable=False),
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('extra_', sa.VARCHAR(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('is_channel', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.SMALLINT(), nullable=False),
    sa.Column('source_id', sa.BIGINT(), nullable=False),
    sa.Column('index', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('album_id', sa.BIGINT(), nullable=False),
    sa.Column('audio', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('audio_duration', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('cover', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('short_intro', sa.TEXT(), nullable=False),
    sa.Column('rich_intro', sa.TEXT(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_statics',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('play_counts', sa.BIGINT(), nullable=True),
    sa.Column('subscribe_counts', sa.BIGINT(), nullable=True),
    sa.Column('comment_counts', sa.BIGINT(), nullable=True),
    sa.Column('like_counts', sa.BIGINT(), nullable=True),
    sa.Column('track_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=256), nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=256), nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('intro', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('user_type', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_table('user')
    op.drop_table('track_statics')
    op.drop_table('track')
    op.drop_table('tag')
    op.drop_table('category')
    op.drop_table('album_tag_pivot')
    op.drop_table('album_statics')
    op.drop_index(op.f('ix_album_title'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
